apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainservice-gke
  labels:
    app:mainservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mainservice
  template:
    metadata:
      labels:
        app: mainservice
    spec:
      containers:
      - name: mainservice
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/directfn/mainservice-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

