apiVersion: v1
kind: Service
metadata:
  name: mainservice
spec:
  selector:
    app: mainservice
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30036
    protocol: TCP